export type SquadInfo = {tag: string, slots: number, with: string[], without: string[]};

export const SQUADS_INFO : SquadInfo[] = [
    {tag: 'AS', slots: 7, with: ['st31'], without: ['GROM', 'OT']},
    {tag: 'DKK', slots: 10, with: ['AS', 'FNX', 'IT', 'VOG'], without: ['OT', 'RAF', 'RL', 'W8', 'Wagner']},
    {tag: 'inTeam', slots: 13, with: ['st31', 'AS', 'GROM', 'RAF', 'WD'], without: ['BAT', 'CU', 'IT', 'W8', 'Wagner']},
    {tag: 'RAF', slots: 8, with: ['st31', 'AV', 'inTeam', 'OT'], without: ['Apex', 'TAG', 'WD']},
    {tag: 'FB', slots: 12, with: ['st31', 'AV', 'GROM'], without: ['CU', 'TAG']},
    {tag: 'WD', slots: 8, with: ['AS', 'FB', 'inTeam', 'RON', 'TAG'], without: ['AXE', 'BAT', 'IT', 'ODN', 'OT', 'RL']},
    {tag: 'TAG', slots: 12, with: ['AS', 'AV', 'GROM', 'OT', 'RON'], without: ['inTeam', 'IT', 'RAF', 'RL', 'SGYR']},
    {tag: 'ISKRA', slots: 12, with: ['st31', 'AS', 'AV', 'RON', 'TAG'], without: ['Apex', 'AXE', 'CU', 'ODN', 'VOG']},
    {tag: 'V', slots: 8, with: ['st31', 'AS', 'AV', 'TAG'], without: ['KSK', 'OT']},
    {tag: 'BAKR', slots: 6, with: ['st31', 'AV', 'KSK', 'RON', 'WD'], without: ['AXE', 'CU']},
    {tag: 'Apex', slots: 12, with: ['st31', 'AV', 'FB', 'MSF', 'RON'], without: ['BAT', 'CU', 'ODN', 'OT', 'V']},
    {tag: 'RON', slots: 8, with: ['st31', 'AS', 'ORK', 'RT',  'VOG'], without: ['inTeam', 'ODN', 'RL', 'SGYR', 'Wagner']},
    {tag: 'ODN', slots: 12, with: ['BAT', 'GROM', 'KSK', 'RL', 'SGYR'], without: ['Apex', 'AXE', 'BAKR', 'TAG', 'Wagner']},
    {tag: 'RL', slots: 16, with: ['AS', 'BAT', 'FNX', 'ORK', 'RON', 'WD'], without: ['CU', 'RAF']},
    {tag: 'Wagner', slots: 8, with: ['st31', 'GROM', 'KSK', 'RON', 'W8'], without: ['BAKR', 'CU', 'inTeam', 'TAG']},
    {tag: 'BCS', slots: 10, with: ['st31', 'CBR', 'KSK', 'RAF', 'WD'], without: ['AV', 'AXE', 'BAT', 'CU']},
    {tag: 'OT', slots: 10, with: ['st31', 'AV', 'W8'], without: ['AS', 'DKK', 'inTeam', 'WD']},
    {tag: 'BAT', slots: 11, with: ['st31', 'AXE', 'OT', 'RAF', 'TAG'], without: ['Apex', 'CU', 'KSK', 'RT']},
    {tag: 'AXE', slots: 10, with: ['AV', 'RAF', 'RT',  'TAG', 'VOG'], without: ['BCS', 'inTeam', 'ODN', 'OT', 'RL']},
    {tag: 'ORK', slots: 8, with: ['OT', 'TAG', 'W8'], without: ['st31', 'GROM', 'ISKRA', 'KSK', 'RON']},
    {tag: 'st31', slots: 12, with: ['AV', 'AXE', 'FB', 'GROM', 'OT'], without: ['Apex', 'BAT', 'inTeam', 'RL', 'SGYR']},
    {tag: 'GROM', slots: 9, with: ['st31', 'FB', 'GROM', 'RON'], without: ['Apex', 'AS', 'CU', 'OT', 'RAF', 'WD']},
    {tag: 'KSK', slots: 10, with: ['st31', 'AV', 'FB', 'RAF', 'WD'], without: ['BAT', 'BCS', 'RL', 'SGYR', 'TAG']},
    {tag: 'IT', slots: 12, with: ['st31', 'AV', 'FNX', 'GROM', 'TAG'], without: ['CU', 'DKK', 'ISKRA', 'ORK', 'RL', 'Wagner']},
    {tag: 'SGYR', slots: 8, with: ['st31', 'AXE', 'inTeam', 'MSF', 'RAF'], without: ['CU', 'OT', 'RON', 'W8']},
    {tag: 'RT', slots: 10, with: ['AS', 'RL', 'RON', 'TAG', 'VOG'], without: ['BAKR', 'BAT', 'Wagner']},
    {tag: 'VOG', slots: 10, with: ['AS', 'ISKRA', 'RON', 'RT',  'W8'], without: ['st31', 'GROM', 'ODN', 'RAF', 'Wagner']},
    {tag: 'MSF', slots: 8, with: ['st31', 'Apex', 'AV', 'AXE', 'RAF'], without: ['GROM', 'inTeam', 'ODN', 'W8', 'Wagner']},
    {tag: 'CBR', slots: 9, with: ['st31', 'AV', 'CBR', 'CU', 'RAF'], without: ['AXE', 'FNX', 'IT', 'W8']},
    {tag: 'CU', slots: 8, with: ['st31', 'AS', 'AV', 'AXE', 'OT'], without: ['BAKR', 'BAT', 'BCS', 'IT', 'RL']},
    {tag: 'FNX', slots: 10, with: ['Apex', 'AV', 'TAG', 'W8'], without: ['st31', 'BAT', 'OT', 'RL', 'RON']},
    {tag: 'AV', slots: 10, with: ['st31', 'AXE', 'CU', 'OT', 'RAF'], without: ['BAT', 'CBR', 'inTeam', 'SGYR', 'W8']},
    {tag: 'W8', slots: 13, with: ['AV', 'AXE', 'FNX', 'KSK', 'OT'], without: ['inTeam', 'IT', 'RAF', 'RL', 'SGYR']},
]